name = "testst7735"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["mehdi"]
maintainers = ["mehdi <mbdj@free.fr>"]
maintainers-logins = ["github-mbdj"]

executables = ["testst7735"]
